<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ioAutomaton" nsURI="ioAutomaton" nsPrefix="elite">
  <eClassifiers xsi:type="ecore:EClass" name="IOAutomaton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" ordered="false"
        upperBound="-1" eType="ecore:EClass ../interactionTable/interactionTable.ecore#//State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" ordered="false"
        upperBound="-1" eType="ecore:EClass ../behaviourTable/behaviourTable.ecore#//Behaviour"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="ecore:EClass ../interactionTable/interactionTable.ecore#//CommObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="ecore:EClass ../interactionTable/interactionTable.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomatonPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="automatons" upperBound="-1"
        eType="#//IOAutomaton"/>
  </eClassifiers>
</ecore:EPackage>
