<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interactionMetamodel" nsURI="interactionMetamodel" nsPrefix="elite">
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="occurencespecification"
        upperBound="-1" eType="#//OccurenceSpecification" eOpposite="#//OccurenceSpecification/lifeline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendEvent" eType="#//MessageOccurenceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveEvent" eType="#//MessageOccurenceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSort" eType="#//MessageSort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageOccurenceSpecification" eSuperTypes="#//OccurenceSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateInvariant" eSuperTypes="#//OccurenceSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifelines" upperBound="-1"
        eType="#//Lifeline" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageSort">
    <eLiterals name="synchCall"/>
    <eLiterals name="asynchCall" value="1"/>
    <eLiterals name="reply" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccurenceSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" lowerBound="1"
        eType="#//Lifeline" eOpposite="#//Lifeline/occurencespecification"/>
  </eClassifiers>
</ecore:EPackage>
