<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="synthesis" nsURI="http://www.example.org/synthesis" nsPrefix="synthesis">
  <eClassifiers xsi:type="ecore:EClass" name="InteractionTable">
    <eOperations name="project" eType="#//InteractionTable">
      <eParameters name="actor" eType="#//Actor"/>
    </eOperations>
    <eOperations name="behaviour" eType="#//Behaviour">
      <eParameters name="actor" eType="#//Actor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
        eType="#//Communication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserActor" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemObject" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Behaviour"/>
  <eClassifiers xsi:type="ecore:EClass" name="Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//UserActor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReturnType">
    <eLiterals name="void"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preState" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postState" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="return" eType="#//ReturnType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//SystemObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonState" eSuperTypes="#//State"/>
</ecore:EPackage>
